/*
PROBLEM: Power Prediction for a Hydroelectric Dam
ANALYSIS: To solve this problem, we need to calculate the power generated by water flowing over a dam.
The input includes the height of the dam and the flow rate of water in cubic meters per second. We use the
formula for work done by gravity (w = mgh), where 'm' is mass, 'g' is gravitational constant, and 'h' is height.
The power generated is the work per second, and we are given that 90% of this energy is converted to electrical energy.

DATA REQUIREMENTS:
Problem Inputs:
double height; // Height of the dam in meters
double flow_rate; // Water flow rate in cubic meters per second

Problem Outputs:
double power_MW; // Power produced in megawatts (MW)
double work_done; // Work done by gravity in joules per second (watts)
double efficiency = 0.9; // Efficiency factor (90%)
double g = 9.80; // Gravitational acceleration (m/s^2)

DESIGN:
INITIAL ALGORITHM:
Step1. Read the height of the dam.
Step2. Read the flow rate of water.
Step3. Calculate the mass of the water per second (mass = flow_rate * 1000).
Step4. Calculate the work done by gravity (work_done = mass * g * height).
Step5. Calculate the power generated by converting 90% of the work to electrical energy.
Step6. Convert the power to megawatts (MW).
Step7. Display the predicted power in megawatts.

IMPLEMENTATION:
*/

#include <stdio.h>

int main() {
    // Constants
    const double g = 9.80;           // Gravitational constant (m/s^2)
    const double efficiency = 0.90;  // Efficiency of energy conversion (90%)
    
    // Variables
    double height, flow_rate, mass, work_done, power_W, power_MW;
    
    // Input: Height of the dam and flow rate of water
    printf("HYDROELECTRIC DAM POWER PREDICTOR\n");
    printf("Enter the height of the dam (in meters): ");  // Step 1
    scanf("%lf", &height);  // Step 2
    
    printf("Enter the flow rate of water (in cubic meters per second): ");  // Step 3
    scanf("%lf", &flow_rate);  // Step 4
    
    // Calculations
    mass = flow_rate * 1000;  // Step 5: Mass of water (kg) = flow rate * 1000 kg/m^3
    work_done = mass * g * height;  // Step 6: Work done (Joules/second or Watts)
    power_W = work_done * efficiency;  // Step 7: Power produced in watts after considering efficiency
    power_MW = power_W / 1e6;  // Step 8: Convert watts to megawatts (MW)
    
    // Output: Power produced in megawatts
    printf("The predicted power produced is %.2f megawatts (MW).\n", power_MW);  // Step 9
    
    return 0;
}
